name: Test
on:
  workflow_call:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Check for formatting errors
        run: npm run format
      - name: Check for eslint
        run: npm run lint
      - name: check for type errors
        run: npm typecheck
      - name: build project
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: .next/
      - name: Run unit tests
        run: npm run test
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run e2e tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
